export const FETCH_WEATHER_API = 'weather/FETCH_WEATHER_API'
export const FETCH_WEATHER_LIST_API = 'weather/FETCH_WEATHER_LIST_API'
export const FETCH_WEATHER_FORECAST_API = 'weather/FETCH_WEATHER_FORECAST_API'
